version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: feago
    main: ./cmd/feago
    binary: feago
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/afrxo/feago/internal.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: feago
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: afrxo
    name: feago
  draft: false
  prerelease: auto
  mode: replace

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

homebrew_casks:
  - name: feago
    repository:
      owner: afrxo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/afrxo/feago
    description: Rojo project generator that organizes Roblox code by feature instead of realm
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    hooks:
      post:
        install: |
          if OS.mac? && File.exist?("#{staged_path}/feago")
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/feago"]
          end
